### ISSUE TITLE
Balances are too small but higher than 0 isn't shown when you select Hide Zero Balances

### ISSUE THREAD

**Issue by memoyil** [beefyfinance/beefy-app#109]
When balances are too small but higher than 0 it doesn't show when you select Hide Zero Balances.

If you have LP balances like 0.00006482 it isn't showed up in the list when you select that filter. Deposited Vault works though.

**Comment by wivern-co-uk** [comment]
Hi @memoyil, could you please share your wallet address (maybe DM on discord) or at least name which exact LP you are having an issue with? This way it will be easier to reproduce and fix.

**Comment by memoyil** [comment]
Sorry i will not share my wallet address with you but it happens in Ditto-BNB LP where LP value is so high that I only have 0.00006xxx it

**Comment by wivern-co-uk** [comment]
> Sorry i will not share my wallet address with you but it happens in Ditto-BNB LP where LP value is so high that I only have 0.00006xxx it

Thanks for the details @memoyil, managed to reproduce an issue, fix is on its way...

**Comment by wivern-co-uk** [comment]
Hey, @memoyil an improvement have been merged to prod, could you check it works for you now?

**Comment by memoyil** [comment]
It works thank you

**Comment by sirbeefalot** [comment]
Closed by https://github.com/beefyfinance/beefy-app/pull/116
