### ISSUE TITLE
The wrong balance displayed after deposit

### ISSUE THREAD

**Issue by qwinkler** [beefyfinance/beefy-app#118]
I got 355 BUSD and deposited them into the `BUSD x AUTO` vault. I got `mooAutoBusd` tokens back. Their quantity was the same as I deposited, but on the UI I saw that the count of deposited money is less. And for now, I have more `mooAutoBusd` tokens, than the balance on the website. Is it expected behavior?

![image](https://user-images.githubusercontent.com/18363937/107851348-fb076f80-6e11-11eb-896e-8c29f841a88f.png)
![image](https://user-images.githubusercontent.com/18363937/107851357-0b1f4f00-6e12-11eb-8639-03457cfbf821.png)

**Comment by roman-monk** [comment]
you got less deposited money because there is ~0.1% fee on deposit and there will be no withdrawal fee.

![image](https://user-images.githubusercontent.com/71946691/107872790-bbab5280-6ee7-11eb-9729-191c04d39cc8.png)

**Comment by sirbeefalot** [comment]
Closed as @roman-monk is correct. It's due to the Autofarm 0.1% deposit fee.
