### ISSUE TITLE
Add a BNB "Zap" feature to the app for conveniency. ($4000 Bounty)

### ISSUE THREAD

**Issue by sirbeefalot** [beefyfinance/beefy-app#122]
## Context
We're always looking to improve the experience and remove friction of users interacting with Beefy.
Having to create an LPs can sometimes be a hassle, especially for new users. 

## Solution
We would like to add a "Zap" feature from BNB and to BNB. This means that:
1. Users can come in with BNB, and through the Beefy UI, swap it for the LP that a vault can manage.
2. Users that want to withdraw from a vault, can from the the LP into BNB with one click as well.
I don't exactly know if this is best solved at the smart contract level, at the client level, or if both would have to be involved.

## Notes
- It might be desirable, even in the first version, for people to toggle the accepted slippage. Otherwise we might configure the slippage at something low initially. 
- In the future, the functionality will probably be extended to allow zaps from more currencies.

**Comment by pedrokehl** [comment]
Hi @sirbeefalot , I'm interested in working on this, but I have a few questions before I start working.

1. Are there more detailed Acceptance Criteria described somewhere or it's kinda open to implement how I think it would be the best, and leave the final approval for the code review?
2. Is this implementation gonna be open to everyone and whoever does it first gets the bounty, or I can mark this as "in progress" so we avoid duplicated work from different people?

**Comment by Code0x2** [comment]
> ## Context
> We're always looking to improve the experience and remove friction of users interacting with Beefy.
> Having to create an LPs can sometimes be a hassle, especially for new users.
> 
> ## Solution
> We would like to add a "Zap" feature from BNB and to BNB. This means that:
> 
> 1. Users can come in with BNB, and through the Beefy UI, swap it for the LP that a vault can manage.
> 2. Users that want to withdraw from a vault, can from the the LP into BNB with one click as well.
>    I don't exactly know if this is best solved at the smart contract level, at the client level, or if both would have to be involved.
> 
> ## Notes
> * It might be desirable, even in the first version, for people to toggle the accepted slippage. Otherwise we might configure the slippage at something low initially.
> * In the future, the functionality will probably be extended to allow zaps from more currencies.

I have a contract for this working on mainnet for eth. check it out at [instadefi.io](https://instadefi.io). is that something you want?

**Comment by sirbeefalot** [comment]
> Hi @sirbeefalot , I'm interested in working on this, but I have a few questions before I start working.
> 
> 1. Are there more detailed Acceptance Criteria described somewhere or it's kinda open to implement how I think it would be the best, and leave the final approval for the code review?
> 2. Is this implementation gonna be open to everyone and whoever does it first gets the bounty, or I can mark this as "in progress" so we avoid duplicated work from different people?

There isn't a detailed acceptance criteria, we can work it out together. A key thing is that it has to be a scalable solution that we can use with 100-500 vaults and in multiple chains without much change besides config.

**Comment by sirbeefalot** [comment]
> > ## Context
> > We're always looking to improve the experience and remove friction of users interacting with Beefy.
> > Having to create an LPs can sometimes be a hassle, especially for new users.
> > ## Solution
> > We would like to add a "Zap" feature from BNB and to BNB. This means that:
> > 
> > 1. Users can come in with BNB, and through the Beefy UI, swap it for the LP that a vault can manage.
> > 2. Users that want to withdraw from a vault, can from the the LP into BNB with one click as well.
> >    I don't exactly know if this is best solved at the smart contract level, at the client level, or if both would have to be involved.
> > 
> > ## Notes
> > 
> > * It might be desirable, even in the first version, for people to toggle the accepted slippage. Otherwise we might configure the slippage at something low initially.
> > * In the future, the functionality will probably be extended to allow zaps from more currencies.
> 
> I have a contract for this working on mainnet for eth. check it out at [instadefi.io](https://instadefi.io). is that something you want? It allows for conversion between LP->LP, but I can add a feature to allow single asset zap-ins

Yeah, it's more or less what we're looking for. We're trying to got it integrated seamlessly into the vaults UI, and not in a separate screen for example. The conversion on our case would pretty much always be Single Asset --> LP

**Comment by Code0x2** [comment]
> > > ## Context
> > > We're always looking to improve the experience and remove friction of users interacting with Beefy.
> > > Having to create an LPs can sometimes be a hassle, especially for new users.
> > > ## Solution
> > > We would like to add a "Zap" feature from BNB and to BNB. This means that:
> > > 
> > > 1. Users can come in with BNB, and through the Beefy UI, swap it for the LP that a vault can manage.
> > > 2. Users that want to withdraw from a vault, can from the the LP into BNB with one click as well.
> > >    I don't exactly know if this is best solved at the smart contract level, at the client level, or if both would have to be involved.
> > > 
> > > ## Notes
> > > 
> > > * It might be desirable, even in the first version, for people to toggle the accepted slippage. Otherwise we might configure the slippage at something low initially.
> > > * In the future, the functionality will probably be extended to allow zaps from more currencies.
> > 
> > 
> > I have a contract for this working on mainnet for eth. check it out at [instadefi.io](https://instadefi.io). is that something you want? It allows for conversion between LP->LP, but I can add a feature to allow single asset zap-ins
> 
> Yeah, it's more or less what we're looking for. We're trying to got it integrated seamlessly into the vaults UI, and not in a separate screen for example. The conversion on our case would pretty much always be Single Asset --> LP

I can get the contracts working. Im ass at making websites though lol

**Comment by pedrokehl** [comment]
> > Hi @sirbeefalot , I'm interested in working on this, but I have a few questions before I start working.
> > 
> > 1. Are there more detailed Acceptance Criteria described somewhere or it's kinda open to implement how I think it would be the best, and leave the final approval for the code review?
> > 2. Is this implementation gonna be open to everyone and whoever does it first gets the bounty, or I can mark this as "in progress" so we avoid duplicated work from different people?
> 
> There isn't a detailed acceptance criteria, we can work it out together. A key thing is that it has to be a scalable solution that we can use with 100-500 vaults and in multiple chains without much change besides config.
> 
> If you're committed and think you can get it done, we can let people know that there's someone already working on it to prevent wasted work.

Hi @sirbeefalot ,
Thank you for your answer.

I already "designed" the idea in my mind, and I will be working on it in the next few days. If for some reason I won't be able to finish it, I will let you know here.

**Comment by LeChuckBerry** [comment]
I do not feel confident I have the skills for this, but I just wanted to point out that a competitor has this function : 
[Contract code](https://github.com/PancakeBunny-finance/Bunny/blob/main/contracts/zap/Zap.sol) 
[UI and functionnality](https://pancakebunny.finance/zap)
It could help inspire this feature.

**Comment by wivern-co-uk** [comment]
On it!
