### ISSUE TITLE
Remove LP duplicate images to decrease load time

### ISSUE THREAD

**Issue by sirbeefalot** [beefyfinance/beefy-app#139]
Right now we use custom images for different vaults even if they use the same LP. For example the ETH-BNB vault that uses Pancakeswap has a different image than the ETH-BNB vault that uses jetfuel, or the one from Streetswap. 

If we stopped separating token/lp images in folders, and use the same assets for each LP/token it would diminish load time.

**Comment by roman-monk** [comment]
fixed in https://github.com/beefyfinance/beefy-app/pull/161
