### ISSUE TITLE
Wrapping static word from pools.js to i18n for localization

### ISSUE THREAD

**Issue by dotX12** [beefyfinance/beefy-app#155]
I wanted to translate this, but I see that this is a static word, is it possible to recycle pools.js and transfer from the tokenDescription key "Uses:"

![image](https://user-images.githubusercontent.com/64792903/108777679-3c67ef80-7575-11eb-9ca8-2118ccb73df8.png)
![image](https://user-images.githubusercontent.com/64792903/108777705-4853b180-7575-11eb-9ef7-0fbd2a426c83.png)

**Comment by roman-monk** [comment]
done https://github.com/beefyfinance/beefy-app/pull/240
