### ISSUE TITLE
Make app work without wallet connection

### ISSUE THREAD

**Issue by FloorLamp** [beefyfinance/beefy-app#158]
* Use a default web3 provider
* Display TVL and APYs
* Prompt user to collect wallet upon clicking an action button

**Comment by roman-monk** [comment]
we used to have it before, but it was lost after saving filters to local storage i think.
also Superb had some points to always show wallet dialog (unless you connected before) no matter if we can load data without it or not

**Comment by sirbeefalot** [comment]
I think that @superbeefyboy point was mostly because we were showing a bunch of ???. But properly done, @FloorLamp proposal might be pretty good. A couple of the Beefy admins have asked me to implement it at least.

**Comment by wivern-co-uk** [comment]
@sirbeefalot let me know if we are missing anything from api side to make it happen.

**Comment by nienow** [comment]
- [x] Use a default web3 provider
- [x] Display TVL and APYs
- [ ] Prompt user to collect wallet upon clicking an action button

2 of 3 tasks done.

**Comment by nienow** [comment]
Issue is complete
