### ISSUE TITLE
Add a "Stable" filter to show all stablecoin vaults

### ISSUE THREAD

**Issue by sirbeefalot** [beefyfinance/beefy-app#17]
Add another filter where users can find vaults which use USDC/USDT/BUSD/DAI/VAI/etc

This could be a misc filter where another option is "LP Tokens" and "Single assets" maybe?

**Comment by roman-monk** [comment]
@sirbeefalot how about Singles, StableLPs, Stables?

![image](https://user-images.githubusercontent.com/71946691/102007053-ab98ba80-3d60-11eb-802c-fa2b69045e08.png)

**Single Assets** - means all singles, not only stables but also Cake, BIFI Maxi or LINK. 
idea that it's a conservative Vault with no impermanent loss

**Stable LPs** - LPs where both assets are stablecoins, and IL is minimum.
(maybe also add single stablecoin vaults here)

**Stables** - all vaults with at least 1 stablecoin asset, including Singles and StableLPs

A bit complicated maybe, but i think great to highlight vaults with single BNB/ETH too

**Comment by sirbeefalot** [comment]
I like it.

Maybe those types of filters should eventually go into their own dropdown. And "Asset" should actually be a search bar of  coins, as a dropdown with 50-100 items is questionable UX.

**Comment by roman-monk** [comment]
i think even now search bar would be nice, 30 assets already
created new issue https://github.com/beefyfinance/beefy-app/issues/26
