### ISSUE TITLE
Add a 'Reset Filters' action to the filter section

### ISSUE THREAD

**Issue by DefiDebauchery** [beefyfinance/beefy-app#175]
Very frequently, when users report issues with not seeing certain vaults, it's due to past filters continuing to be applied.

Having these saved in localStorage is not a bad idea to keep (166a2d6aaf7428619b4652cb5e2a4dd8fab6f704), but there should be quick access to reset this filter. This will mitigate several back-and-forth queries of "Do you have <this> filter set?", as well give other users an easy way to knowingly reset their settings.

![Screen Shot 2021-02-28 at 7 44 18 PM](https://user-images.githubusercontent.com/75273961/109439694-69952180-79fd-11eb-8f28-7fd0b1a4bda8.png)

**Comment by roman-monk** [comment]
And highlight this button if there are filters activated. Or do not show it until user toggle any filter, to make it more visible

**Comment by sirbeefalot** [comment]
Yes, having a pretty noticeable "Reset Filters" button that's shown only when a filter is applied would be good.
