### ISSUE TITLE
Remove all the warnings from the new 'stake' section. 

### ISSUE THREAD

**Issue by sirbeefalot** [beefyfinance/beefy-app#196]
We've had to add DFI code again to the app. This comes with 1000 different warnings like always. It'd be good to clean them up.

**Comment by BrightReach** [comment]
I'd like to give that a go. Are you able to direct me to which file(s) I'll need to clean the code from?

**Comment by sirbeefalot** [comment]
Hi @BrightReach, @fstar just started working on this one. Want me to prepare 1-2 starter issues custom made for you? :)

**Comment by sirbeefalot** [comment]
Genius, will do that. Today I'm not gonna be able due to irl stuff, but I'll do it tomorrow.

**Comment by BrightReach** [comment]
Looking forward to working with you. 😁

**Comment by roman-monk** [comment]
Hey @BrightReach, i think you can work on this one, as no feedback from @fstar for a long time.
To see warnings simply "yarn start" and you will have bunch of them in logs:
```
./src/features/stake/sections/StakePools.js
  Line 113:62:   Unexpected mix of '&&' and '||'  no-mixed-operators
  Line 113:99:   Unexpected mix of '&&' and '||'  no-mixed-operators
  Line 113:99:   Unexpected mix of '||' and '&&'  no-mixed-operators
  Line 113:125:  Unexpected mix of '||' and '&&'  no-mixed-operators
  Line 113:160:  Unexpected mix of '||' and '&&'  no-mixed-operators
  Line 113:186:  Unexpected mix of '||' and '&&'  no-mixed-operators

./src/features/vault/components/Pool/Pool.js
  Line 1:46:   'useEffect' is defined but never used         no-unused-vars
  Line 12:10:  'useFetchPoolData' is defined but never used  no-unused-vars

./src/features/stake/sections/StakePool.js
  Line 43:14:   'i18n' is assigned a value but never used   
```

**Comment by PCRyan** [comment]
@roman-monk Was this successfully assigned? If not, I'm happy to tackle it as further introduction to the codebase.

**Comment by roman-monk** [comment]
Take it please!

**Comment by PCRyan** [comment]
@roman-monk Cool, ready to start. Do you want/need to assign me? I see no way to explicitly "take" the issue.
