### ISSUE TITLE
Responsive issue for Header between Large (1280px) and Medium (960px) breakpoints

### ISSUE THREAD

**Issue by BrightReach** [beefyfinance/beefy-app#211]
# Context
When the app's width is set between 1280px to 960px, there will be missing links such as barn, vote, etc. That would be an issue for anybody who's using the iPad or any tablet that utilises that website width.

The bug was found on Safari on iPad Mini and Version 88.0.4324.190 (Official Build) (64-bit).

## Reproduction for Bug
1. Load the app
2. Press Ctrl+Shift+I to access Developer Tools on Chrome.
3. Click on Toggle Device Toolbar or press Ctrl+Shift+M
4. Underneath the address bar where you can see Responsive and the dimensions for width and length, set the width from 1279px to 960px.
5. Observe the header where you can see the 'buy' and 'BOOST' button but unable to see either the other buttons or the sidebar burger button.

# Solution
I'm proposing to change the breakpoints and ensure that the users can access the sidebar menu when using a tablet.

**Comment by sirbeefalot** [comment]
You're right. I saw this but didn't realize it was a bug. What do you think about removing the header icons and just making the words capitalized to reduce the space it takes? I think there's consensus that the icons are unnecessary at this point.

We might be able to go do a lower resolution before switching to the sidebar menu layout.

**Comment by BrightReach** [comment]
Definitely worth removing the headers icons. Or better yet, have the links with two rows with some padding between them.
