### ISSUE TITLE
Add BSC network config for Metamask

### ISSUE THREAD

**Issue by roman-monk** [beefyfinance/beefy-app#213]
Add 1-click option to configure BSC network in Metamask and switch to it.

Implemented by PCS recently 
https://twitter.com/PancakeSwap/status/1369177840915148800
with this commit
https://github.com/pancakeswap/pancake-frontend/commit/35e83a52427ab6e9eb7227e19f76c2fe56f797a1

**Comment by wivern-co-uk** [comment]
On it!
