### ISSUE TITLE
App crashes if you scroll down to the bottom without any filter

### ISSUE THREAD

**Issue by sirbeefalot** [beefyfinance/beefy-app#295]
# Problem
Right now we have 220 vaults and for various reasons, not all of them good, we have a lot of re-rendering of elements. Those two things combined slow down React. Adding an infinite loader library improved things, as it used to happen all the time. 

# Solution
I have a couple solutions that might work:
1- Decrease re-rendering: Figure out if we can optimize the app and remove some of the re-renders that happen.
2- Replace infinite scroll for react-window or react-virtualized. This might be the killer solution if we can make it happen.
3- Make one of the category filters something that always has to be selected. For example you can only see single assets, or LP tokens. This way users would not be able to scroll all vaults. This one is more a patch than a solution tbh.

**Comment by roman-monk** [comment]
was fixed here https://github.com/beefyfinance/beefy-app/pull/298
