### ISSUE TITLE
Tx notifications should direct to the correct explorer depending on chain.

### ISSUE THREAD

**Issue by sirbeefalot** [beefyfinance/beefy-app#386]
Right now when you do a successful transaction you get a snack bar with the transaction hash and a button to see it in the blockchain explorer.

The problem is that transactions from all chains direct to BSCScan. We should make this dynamic and go to the correct explorer for each chain. 

We're going to be adding more chains, so it should be easy to extend it, there's a [src/common/networkSetup.js](https://github.com/beefyfinance/beefy-app/blob/master/src/common/networkSetup.js) file that could be useful to get the relevant config for the UI

**Comment by Kalesberg** [comment]
will take a look
