### ISSUE TITLE
Improve depositing user experience

### ISSUE THREAD

**Issue by mjoaris** [beefyfinance/beefy-app#391]
### Current issue
Currently, it takes over 35 seconds after clicking "Deposit All" for the user's funds to appear under the "Deposited: " field.

Timeline of events after "Deposit All"
0 seconds - hit deposit all
9 seconds - deposit transaction is confirmed
21 seconds - deposit successful
35 seconds - deposit is now properly displayed under "Deposited: "

### Proposed solution / improvements
**I would like to request a forced user balance update after depositing.**
This action can be set to work after the transaction receipt of the successful deposit is included in the respective block, so after 21 seconds.

This would shave off 14 seconds from the current timeline of events.

**Comment by ReflectiveChimp** [comment]
If anyone picks this up, I believe we would need to call `fetchBalances({ address, web3, tokens });` from the `fetchDeposit` / `fetchDepositBnb` callbacks (i.e. on deposit tx receipt) in https://github.com/beefyfinance/beefy-app/blob/f6f24085677ff814a587838d2b7fbc7811ecb5f0/src/features/vault/components/PoolDetails/DepositSection/DepositSection.js#L81 and https://github.com/beefyfinance/beefy-app/blob/f6f24085677ff814a587838d2b7fbc7811ecb5f0/src/features/vault/components/PoolDetails/DepositSection/DepositSection.js#L93

**Comment by wivern-co-uk** [comment]
This is alreasy fixed in the zap branch! #249
