### ISSUE TITLE
Automatic cache bust on each app deploy

### ISSUE THREAD

**Issue by sirbeefalot** [beefyfinance/beefy-app#415]
Right now when we make a change to the API that we want the app to reflect, we need to update the timestamp of two files manually.  

- [fetchApys.js](https://github.com/beefyfinance/beefy-app/blob/master/src/features/vault/redux/fetchApys.js)
- [fetchPrice.js](https://github.com/beefyfinance/beefy-app/blob/master/src/features/web3/fetchPrice.js)

The query string doesn't need to be a timestamp, it just needs to be something unique to force the API to bust the cache and fetch the current values. 

It'd be great to make it so that this changes automatically with each deploy or commit, because otherwise it's extra work and we will sometimes forget to update it.

It should not become something that updates every x seconds though, as we don't want to overload the API.

**Comment by ReflectiveChimp** [comment]
Suggestion:

Remove the _ parameter from the url in beefy-app.

Update beefy-api to [purge the CloudFlare cache](https://api.cloudflare.com/#zone-purge-files-by-url) the first (or every) time `updateAmmPrices`/`updateApys` etc finish running.

This can be done on a per-url basis.

Will require beefy-api to have access to the CloudFlare API.
Purging a url only requires the `cache_purge:edit` permission so a key could be created for this purpose only.

Doing it this way should mean that beefy-app doesn't need updated when beefy-api is and updates to the API will be available ASAP.

Potential downsides: This is dependent on CloudFlare remaining our CDN provider (although I suspect other providers will also have APIs to purge the cache on a URL by URL basis)

**Comment by roman-monk** [comment]
closed by #483
