### ISSUE TITLE
`Retired Vaults` checkbox is unintuitive 

### ISSUE THREAD

**Issue by Moonster-BSC** [beefyfinance/beefy-app#445]
The UI shows the following messages:

- Hide zero balances
- Retired Vaults
- Deposited Vaults
- Boost

All of these besides `Retired Vaults` filter out the vaults by that checkbox. The `Retired Vaults` checkbox does the opposite: it shows that retired vaults that were previously hidden. This should be changed to either make it consistent with the rest, or improve the messaging to say `Show retired vaults`

**Comment by JordanRaphael** [comment]
Originally all retired vaults were hidden, even if you had deposited amount in one of them. Recently that changed, if you have a deposited amount in a vault, it is automatically visible and is on top of the list, because we had many complaints from users that they couldn't find their funds.
