### ISSUE TITLE
Localize remaining non-doc aspects of app & site

### ISSUE THREAD

**Issue by AllTradesz** [beefyfinance/beefy-app#515]
Localize all appropriate elements of
+ Dashboard (via stats link)
+ Gov (via gov link)

If any of this is being overhauled in V2, perhaps now's not the time to address this. Comments?

I'm happy to tackle this as a dev. My dev environment is finally ready to go.

**Comment by PCRyan** [comment]
Based on feedback from @superbeefyboy, only the dashboard is worth addressing.

Taking this on then. If appropriate, please assign issue to me.
