### ISSUE TITLE
Add APY Breakdown Info from API Endpoint apy/breakdown on the APP

### ISSUE THREAD

**Issue by MirthFutures** [beefyfinance/beefy-app#565]
Beefy's App currently displays the Total APY of most AMM's (inclusive of trading APR). What needs to happen is the info from the newly created apy/breakdown endpoint needs to be displayed on the app.  At bare minimum a display for Total APY, Vault APY, Trading APR, Daily APY and TVL is needed.

**Comment by ReflectiveChimp** [comment]
Can I request that we don't have hovers? If you want the information hidden until a user interaction, perhaps some dropdown toggle similar to the way the vault card opens.

Hovers don't always work great on touch devices (mobile/tablet), and they often go missed completely as there is no chance to accidently hover over them like you might on desktop.

**Comment by MirthFutures** [comment]
Agree with the feedback. I'll remove from initial post.

**Comment by PCRyan** [comment]
I've seen the no-hover-on-mobile problem resolved by a small-circled-i added at least on the mobile flavor of the app which is clickable with a small, pretty info popup the disappears with the next touch anywhere. On desktop, I do like hovers. My 2 cents.

**Comment by ReflectiveChimp** [comment]
I'm not against them if they work when clicked on mobile, and it is made obvious that they can be clicked.

Trying to avoid the ones like on the chain icons on https://www.beefy.finance/ - works fine on desktop but on mobile there is no way to know they are there until you click it.

**Comment by ReflectiveChimp** [comment]
This can be closed; was added in #573
