### ISSUE TITLE
Create a separate page for each vault. ($500 Bounty)

### ISSUE THREAD

**Issue by sirbeefalot** [beefyfinance/beefy-app#58]
Having a routable page to a vault would help us in a few ways.

1. Deep linking will make it easier to get traction and direct users exactly to a vault that they might be interested.
2. Have more space for relevant info. We could add information relating to impermanent loss for example on LP vaults.
3. Be able to do more queries once we're inside the vault page without concern for doing too many concurrent queries.

**Comment by roman-monk** [comment]
closed by #385
