### ISSUE TITLE
Remove 'lodash' dependency

### ISSUE THREAD

**Issue by sirbeefalot** [beefyfinance/beefy-app#76]
Lodash is a considerable part of our build right now but we only use it for its "find" function. 

We should either replace it for native javascript or just depend on that individual lodash function.

This would increase performance, especially if we're trying to start targeting mobile users more.

**Comment by tonytangdev** [comment]
Hi !

I just started contributing to open source project and I stumbled upon this issue.

Here's the PR : #79

**Comment by shibacrypt** [comment]
@sirbeefalot this has been addressed at https://github.com/beefyfinance/beefy-app/pull/79 and merged, lets close this~
