### ISSUE TITLE
Refactor our stats RPC calls using a Multicall contract.

### ISSUE THREAD

**Issue by sirbeefalot** [beefyfinance/beefy-app#77]
Every time a user opens up the app, we're doing a few hundred RPC calls to the BSC nodes. Some users get rate limited and face weird bugs. As we add more vaults, it becomes more of a problem. 

We should deploy a Multicall contract on BSC and use it to turn all those requests into 1-3

**Comment by PabiGamito** [comment]
@sirbeefalot Has a multicall contract been deployed on BSC? And if so, what is its address?
