### ISSUE TITLE
polygon wallet connect

### ISSUE THREAD

**Issue by selman** [beefyfinance/beefy-app#786]
giving this error on chrome and not connecting over trustwallet dapp browser too.

> Resources that failed to load
> A few resources failed to load due to issues with your network, proxy server or the webpage.
> SwitchyOmega is just the reporter of these issues, not the cause of them.
> 
> *.maticvigil.com
>

**Comment by AllTradesz** [comment]
Tech-support issues like this are best handled in over our Discord or Telegram channels. If you follow [this link](https://discord.gg/S35GRRyk8x), you will land in the best spot to report your issue and be helped.

**Comment by roman-monk** [comment]
fixed
